services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: abw-bos

    restart: unless-stopped

    env_file:
      - .env

    ports:
      - "3000:3000"

    labels:
      - traefik.enable=true
      - traefik.http.routers.abw-bos.rule=Host(`crm.abwcurious.com`)
      - traefik.http.routers.abw-bos.entrypoints=websecure
      - traefik.http.routers.abw-bos.tls.certresolver=letsencrypt
      - traefik.http.services.abw-bos.loadbalancer.server.port=3000
      - traefik.docker.network=proxy

    networks:
      - abw-network
      - proxy

networks:
  abw-network:
    external: true

  proxy:
    external: true
